version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: bitrix-nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./bitrix/www:/var/www/html
      - ./bitrix/config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bitrix-net

  php:
    image: bitnami/php-fpm:8.1
    container_name: bitrix-php
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=64M
      - PHP_UPLOAD_MAX_FILESIZE=64M
    volumes:
      - ./bitrix/www:/var/www/html
      - ./bitrix/config/php/php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
    networks:
      - bitrix-net

  mysql:
    image: mysql:8.0
    container_name: bitrix-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bitrix
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=bitrix
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    volumes:
      - ./bitrix/db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - bitrix-net

networks:
  bitrix-net:
    driver: bridge


